services:
  # Frontend service
  - type: web
    name: frontend
    env: node
    plan: free
    buildCommand: |
      cd apps/frontend
      npm install
      npm run build
    startCommand: cd apps/frontend && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_BACKEND_URL
        value: https://my-backend.onrender.com/api/v1  # change after deploying backend

  # Backend service
  - type: web
    name: my-backend
    env: node
    plan: free
    buildCommand: |
      npm install
      cd apps/backend
      npx prisma generate --schema=../../packages/prisma/schema.prisma
      npm run build
    startCommand: cd apps/backend && node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false   # set actual MongoDB URL in Render Dashboard
      - key: JWT_SECRET
        sync: false   # set JWT secret in Render Dashboard
